### ISSUE TITLE
Document OPENWISP_ADMIN_SHOW_USERLINKS_BLOCK setting

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-utils#100]
Add documentation for `OPENWISP_ADMIN_SHOW_USERLINKS_BLOCK` settings in README.rst simialar to what has been done for [other settings](https://github.com/openwisp/openwisp-utils#settings). 
`

@nemesisdesign please add corresponding labels : `good first issue` `GCI`

**Comment by nemesisdesign** [comment]
@TheOneAboveAllTitan :ok: thanks
