### ISSUE TITLE
[bug] Imcompatibility between isort and black

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-utils#101]
When running the command: `openwisp-qa-check` I am seeing an incompatibility between isort and black.

Black wants to convert this to: 
```
-from django_loci.base.models import AbstractFloorPlan, AbstractLocation, AbstractObjectLocation
+from django_loci.base.models import (
+    AbstractFloorPlan,
+    AbstractLocation,
+    AbstractObjectLocation,
+)
```
While isort keeps changing it to:
```
+ from django_loci.base.models import AbstractFloorPlan, AbstractLocation, AbstractObjectLocation
- from django_loci.base.models import (
-     AbstractFloorPlan,
-     AbstractLocation,
-     AbstractObjectLocation,
- )
```

There are many such lines in the django-netjsonconfig.

**Comment by nemesisdesign** [comment]
isort needs to be configured in a certain way to avoid these conflicts:

https://github.com/openwisp/openwisp-firmware-upgrader/blob/master/setup.cfg#L22-L25

```
line_length=88
multi_line_output=3
use_parentheses=True
include_trailing_comma=True
force_grid_wrap=0
```

Explained here (end of the section): https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines

**Comment by atb00ker** [comment]
Yes, it worked, thanks! :smile:
Since these configurations need to be done in the individual repositories instead of here, I am closing it! :smile:
