### ISSUE TITLE
[admin-theme] menu doesn't respect assigned permissions

### ISSUE THREAD

**Issue by okraits** [openwisp/openwisp-utils#103]
The links "Templates" and "VPN Servers" are available in the menu although the user doesn't have the rights for these objects:

![grafik](https://user-images.githubusercontent.com/5543887/81408747-12f0eb00-913e-11ea-95b6-101e109224f2.png)

![grafik](https://user-images.githubusercontent.com/5543887/81408798-2bf99c00-913e-11ea-9c09-62f3baa314f0.png)

I had a look into this a bit:

https://github.com/openwisp/openwisp-utils/blob/master/openwisp_utils/admin_theme/context_processor.py#L32

* `ModelAdmin.has_module_permission` evaluates permissions only on the module level, not on the model level (Device, Template, Vpn).
* `openwisp-utils` is decoupled from the other OpenWISP modules so we don't have access to models etc

**Comment by nemesisdesign** [comment]
@okraits as we discussed, this may work:

1. get the list of permissions of the user (I suggest caching it)
2. build a list of strings, each string representing the app_label and the model name
3. when iterating over the models, we build the string with the app_label and the model name and we check if that string is present in the list built in step 2

**Comment by okraits** [comment]
@nemesisdesign I implemented a fix before I saw your comment :grinning: 

I didn't find a different solution than the one I implemented. Please tell me what you think.
