### ISSUE TITLE
[qa] Post build failure summary information as a comment on github

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#109]
Whenever there's a build failure in a PR, it would be great to know what has failed and post a summary as a comment in the github PR.
I found a blog post which explains how to do it: https://damien.pobel.fr/post/github-api-from-travisci/
But any other updated online resources which work will be fine.

The comment should only have the relevant information about failures an nothing else.

If tests are failing we could simply say "Some test case have failed".

In case `openwisp-qa-check` has failed, we could collect the reason of the failure and post it as a message.

One of the ways in which we could do this is to print errors to standard error (instead of printing to standard output), collect the standard error output in a separate var which is then used to build the comment which will be posted to github. 

I suggest trying this change in your own fork first (enable travis on your fork and test the failures there).

**Comment by KapilBansal320** [comment]
I want to work on this issue

**Comment by nemesisdesign** [comment]
@KapilBansal320 this would be great, I suggest to think about one or more possible solutions and propose it here, feel free to ping us in the chat.

**Comment by KapilBansal320** [comment]
As suggested by you, I will try to run this on my fork first. If it works, then I will propose it.

**Comment by KapilBansal320** [comment]
@nemesisdesign, if some tests failed, then do we need to comment only the error message?
Like, Isort test failed or the reason of its failure too.

**Comment by nemesisdesign** [comment]
Thanks for picking this up @KapilBansal320!

> @nemesisdesign, if some tests failed, then do we need to comment only the error message?
> Like, Isort test failed or the reason of its failure too.
> Or do we need information about the build only ? Like build job failed for which environment and so on.

Well, it would be nice to have a summary of all the info we can get.

Eg:

### [Build 1234](#id-here) failed, python 3.6 / django 3.0

Reason text

### [Build 1235](#id-here) failed, python 3.7 / django 2.2

Reason text

--------------------------------

It depends on what info you can retrieve, but for sure it is important to highlight the reason for which the build failed, if we can also show which build and link to it, that would be incredibly useful for new contributors who may struggle with this part if they're not used to it.

**Comment by KapilBansal320** [comment]
@nemesisdesign , I use travisbuddy for the above task. Please review pull request #141 for this.
