### ISSUE TITLE
[docs] Instructions for development

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-utils#114]
Instructions for development are redundant. Similar to  https://github.com/openwisp/openwisp-users/issues/113#issuecomment-625443317 

In https://github.com/openwisp/openwisp-utils#installing-for-development
Following command does not install dependencies of [qa] and [rest]  which are required for running tests.  
```
python setup.py develop
```

**Comment by KapilBansal320** [comment]
I want to work on this issue.
