### ISSUE TITLE
Implement a base serializer class for API views

### ISSUE THREAD

**Issue by anurag-ks** [openwisp/openwisp-utils#12]
Django-rest-framework, which has been used to create API views, does not call the `full_clean` method under models, this means that custom model validations would not run on API views while creating or updating records. We need to create a base serializer class which can be extended to other apps.

**Comment by nemesisdesign** [comment]
Could be something like:

```python
class ValidatedModelSerializer(serializers.ModelSerializer):
    def validate(self, data):
        instance = self.instance or self.Meta.model(**data)
        instance.full_clean()
        return data
```
