### ISSUE TITLE
[QA] Issue closing not being enforced

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#136]
The check performed at these lines is not being executed:

https://github.com/openwisp/openwisp-utils/blob/fc28a78ac64acc7b8827c6995e2210351f91d1c3/openwisp_utils/qa.py#L155-L163

**Comment by nemesisdesign** [comment]
Confirmed with this test: https://github.com/openwisp/openwisp-utils/pull/137
The QA check should have rejected the commit message.

**Comment by KapilBansal320** [comment]
@nemesisdesign the check you mentioned only executes when there is a long_desc present.
For this we have to test if short_description mentions an issue when long_description is not present. I have made a pull request #138 with necessary changes.
https://github.com/openwisp/openwisp-utils/blob/fc28a78ac64acc7b8827c6995e2210351f91d1c3/openwisp_utils/qa.py#L117-L161

**Comment by nemesisdesign** [comment]
> @nemesisdesign the check you mentioned only executes when there is a long_desc present.
> For this we have to test if short_description mentions an issue when long_description is not present. I have made a pull request #138 with necessary changes.

You're right, I linked the wrong piece of code, I updated the issue description and also replied to your PR with more info, thanks :+1:
