### ISSUE TITLE
[qa] Add ReStructuredText checks to openwisp-qa-check

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#144]
When publishing to pypi, sometimes the publishing fails because of an error in the README.rst, this may happen once the commit and git tag have been already sent, so it's not ideal.

We should avoid this, it shouldn't be hard:

- we can add it to the qa dependencies this tool https://github.com/mgedmin/restview/
- we can add to the qa check a function that calls the rest check (with possibility to skip this), as follows:
  - if README.rst exists, run the check on it
  - if `docs/source` exists, run the check recursively on it

This would allow to enable this check on all the repos which make use of openwisp-utils!

**Comment by KapilBansal320** [comment]
@nemesisdesign please review pull request #145
