### ISSUE TITLE
[bug] ReStructuredText failing for sphinx syntax

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#147]
The ReStructuredText check fails in those repos which are using sphinx, eg: [openwisp-radius](https://github.com/openwisp/openwisp-radius).

```
- <string>:43: (ERROR/3) Unknown directive type "toctree".
- 
- .. toctree::
-    :maxdepth: 2
-    :caption: Contents:
- 
-    /developer/setup
-    /developer/freeradius
-    /user/settings
-    /user/management_commands
-    /user/importing_users
-    /user/generating_users
-    /user/enforcing_limits
-    /user/registration
-    /user/social_login
-    /user/api
-    /developer/how_to_extend
-    /developer/contributing
-    /general/goals
```

@KapilBansal320 can we selectively disable some errors?

**Comment by KapilBansal320** [comment]
I will try to find a solution for that.

**Comment by KapilBansal320** [comment]
> The ReStructuredText check fails in those repos which are using sphinx, eg: [openwisp-radius](https://github.com/openwisp/openwisp-radius).
> 
> ```
> - <string>:43: (ERROR/3) Unknown directive type "toctree".
> - 
> - .. toctree::
> -    :maxdepth: 2
> -    :caption: Contents:
> - 
> -    /developer/setup
> -    /developer/freeradius
> -    /user/settings
> -    /user/management_commands
> -    /user/importing_users
> -    /user/generating_users
> -    /user/enforcing_limits
> -    /user/registration
> -    /user/social_login
> -    /user/api
> -    /developer/how_to_extend
> -    /developer/contributing
> -    /general/goals
> ```
> 
> @KapilBansal320 can we selectively disable some errors?

@nemesisdesign Please review pull request #148 for this.
