### ISSUE TITLE
[enhancement] Change url to path

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#155]
In most of the openwisp modules, "path" has been used and also Django in transitioning to "path". But in this module "url" is being used so I think it should be changed to "path". document may also need to improve in this issue if needed.

**Comment by niteshsinha17** [comment]
@nemesisdesign if this issue is relevant then I would like to work on it.

**Comment by nemesisdesign** [comment]
@niteshsinha17 It's not urgent to do this right now, we should focus our efforts on the issues in the board because we're almost ready to issue new releases of OpenWISP which will benefit the community and that's our goal.

**Comment by niteshsinha17** [comment]
@nemesisdesig I will try to give contributions to those issues for now.

**Comment by 2001asjad** [comment]
@nemesisdesign  Can I take this task?
