### ISSUE TITLE
[deps] Update django-rest-framework to 3.12

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#164]
Before updating the dependency here, we have to test each module that depends on openwisp-utils for DRF (if any module is not depending on openwisp-utils[rest] for DRF yet, we should fix that).

- [ ] openwisp-controller
- [ ] openwisp-network-topology
- [ ] openwisp-notifications
- [ ] openwisp-monitoring
- [ ] openwisp-firmware-upgrader
- [ ] openwisp-radius (https://github.com/openwisp/openwisp-radius/issues/194)

**Comment by ManishShah120** [comment]
Hi, @nemesisdesign we will need to update djangorestframework to `3.12.2`, please see this:- https://github.com/openwisp/openwisp-controller/pull/386#issuecomment-825207951
