### ISSUE TITLE
[feature] Add a custom static storage class

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-utils#166]
Add custom static storage class with option to exclude files based on Unix shell-style wildcards. The code for this new class should reside in `openwisp_utils.storage.py`

Port changes from [storage.py in ansible-openwisp2](https://github.com/openwisp/ansible-openwisp2/blob/d4e05cf502db05c0f48370c37db43585ce39f270/files/storage.py)

**Comment by prsndp** [comment]
Hey, can i work on this issue ?? if yes please assign me.

**Comment by Arsh0023** [comment]
Hi! @pandafy i would like to work on this issue.

**Comment by pandafy** [comment]
Go ahead @Arsh0023 :+1:

**Comment by Arsh0023** [comment]
Hi @pandafy I have created a StaticStoragClass that pretends to ignore files based on Unix shell-style wildcards. So what it actually does is it prevents the files from getting copied to 'STATIC_ROOT'.So first all the files get copied into the 'STATIC_ROOT' and then I've defined a post_process method that deletes the files which were told to be ignored. Is this fine should I create a PR, If not then what changes I should do.

**Comment by pandafy** [comment]
@Arsh0023 you just need to port the code from  [storage.py in ansible-openwisp2](https://github.com/openwisp/ansible-openwisp2/blob/d4e05cf502db05c0f48370c37db43585ce39f270/files/storage.py) which means you can just copy the code for storage class and mixin from there and put it under `openwisp_utils/storage.py`(you'll have to create this file). After that you are supposed to write tests and documentation for the feature.

**Comment by Arsh0023** [comment]
@pandafy Oh I see I went a little out of way, thanks for helping I am actually new to open source. I'd be working on what you told
