### ISSUE TITLE
[qa] Failing commit checks for co-authored commits

### ISSUE THREAD

**Issue by Purhan** [openwisp/openwisp-utils#167]
QA checks have started to fail for commits that are co-authored by one or more users.
For example:
1. https://github.com/openwisp/openwisp-controller/runs/1574632899
2. https://github.com/openwisp/ansible-openwisp2/runs/1546631993

### Expected
These checks should not have failed.

**Comment by devkapilbansal** [comment]
@Purhan I tested it locally but commit message check seems to pass for the same commit message
![commit](https://user-images.githubusercontent.com/42766576/103131971-05867200-46c9-11eb-862f-a7430389a365.png)

**Comment by Purhan** [comment]
@devkapilbansal look at the CI logs I shared, they are using `./run-qa-checks` which is failing.

**Comment by Purhan** [comment]
@devkapilbansal could you please share the output of `pip freeze` for the same here?

Also, once you execute `checkcommit --message "$(git log -1 --pretty=%B)"`, what do you get when you immediately execute `$?` after that?

**Comment by devkapilbansal** [comment]
Here is the output of `pip show openwisp-utils`
![Screenshot from 2020-12-25 21-43-54](https://user-images.githubusercontent.com/42766576/103138675-ee607800-46fa-11eb-9eac-4e4836d4fc7c.png)

**Comment by Purhan** [comment]
@devkapilbansal I meant `echo $?`, just to check the exit code. Anyhow, I'm confused :smile: because it's failing for me (and in the CI builds too), so the bug certainly is there, we should keep this issue open for now.
