### ISSUE TITLE
[QA] Add linting of JS and CSS

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#173]
Add linting of CSS and JS as we do in [openwisp-controller](https://github.com/openwisp/openwisp-controller/) and [openwisp-notifications](https://github.com/openwisp/openwisp-notifications).

Reference:

- https://github.com/openwisp/openwisp-notifications/blob/d7f20ea41bcff1c0a437b93e98cac2d0a3bbec32/.github/workflows/build.yml#L56-L57
- https://github.com/openwisp/openwisp-notifications/blob/d7f20ea41bcff1c0a437b93e98cac2d0a3bbec32/.stylelintrc.json
- https://github.com/openwisp/openwisp-notifications/blob/d7f20ea41bcff1c0a437b93e98cac2d0a3bbec32/.jshintrc
- https://github.com/openwisp/openwisp-notifications/blob/d7f20ea41bcff1c0a437b93e98cac2d0a3bbec32/run-qa-checks#L4-L5

**Comment by shreyash-web** [comment]
i would like to work can i do it

**Comment by prsndp** [comment]
Hi, @nemesisdesign Can I work on this issue, if it is open?

**Comment by nemesisdesign** [comment]
> Hi, @nemesisdesign Can I work on this issue, if it is open?

Sure, go ahead

**Comment by nemesisdesign** [comment]
@niteshsinha17 I think we should do this during your GSoC project since it's very related to what you're doing!

**Comment by niteshsinha17** [comment]
Sure, I will add this. 😄
