### ISSUE TITLE
[release] Release 0.7.4

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#179]
We need to release 0.7.4 to include this: https://github.com/openwisp/openwisp-utils/pull/178
But we don't have to include the new features, so we branch from 0.7.3 and add only bugfixes and then issue a release.

**Comment by nemesisdesign** [comment]
@pandafy is this done? Can we close this?

**Comment by pandafy** [comment]
Yes, this can be closed.
