### ISSUE TITLE
[qa] Commit message check fails if there's a dot after the issue

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#187]
Eg: `Closes #344.`: https://github.com/openwisp/openwisp-controller/runs/2529479318

**Comment by keshavgbpecdelhi** [comment]
Can I do this issue

**Comment by devkapilbansal** [comment]
Sure @keshavgbpecdelhi go ahead

**Comment by keshavgbpecdelhi** [comment]
@devkapilbansal can you tell were to do changes (which code required modification)

**Comment by devkapilbansal** [comment]
I think you need to fix this function
https://github.com/openwisp/openwisp-utils/blob/1f73cc3d522478cd34bd6f10d3dfa98be12e4263/openwisp_utils/qa.py#L83

I tried looking at that issue and found that regex is returning `#344.` from long description which is then matched with `#344` from short description and the tests failed because `#344.` is not same as `#344`

**Comment by keshavgbpecdelhi** [comment]
Do we have to add "." in the skip case?
skip_cases = [
        # merges
        r'^Merge pull request #[A-Za-z0-9.]* from',
        r"^Merge branch '(.*?)' into",
        # releases
        r'^[A-Za-z0-9.]* release$',
        r"^Bumped VERSION to (.*?)$",
        r"^Bump (.*?) from (.*?) to (.*?)$",
    ]

**Comment by keshavgbpecdelhi** [comment]
It is written to add "." 
https://github.com/openwisp/openwisp-utils/blob/1f73cc3d522478cd34bd6f10d3dfa98be12e4263/openwisp_utils/qa.py#L108

**Comment by devkapilbansal** [comment]
It is for short description only

**Comment by devkapilbansal** [comment]
@keshavgbpecdelhi did you tried going throigh the code once and undertand what's going there ? The best way to fix the error is to try reproduce it locally, see which part of code is responsible for that, writing a test case that will fail for sure unless the error is fixed and then solving the error.

**Comment by nemesisdesign** [comment]
@keshavgbpecdelhi first step is to write a failing test to replicate the issue, see https://github.com/openwisp/openwisp-utils/blob/master/tests/test_project/tests/test_qa.py#L79-L135.

**Comment by keshavgbpecdelhi** [comment]
@devkapilbansal copying the code in VS code and running it.
@nemesisdesign what we have to do with failing test? And Where to write it? It is showing this:
https://github.com/openwisp/openwisp-utils/blob/1f73cc3d522478cd34bd6f10d3dfa98be12e4263/tests/test_project/tests/test_qa.py#L79-L135
