### ISSUE TITLE
[docs] Write documentation regarding register menu group functionality

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#190]

**Comment by nemesisdesign** [comment]
I don't understand this issue, isn't this supposed to be part of #189?

**Comment by niteshsinha17** [comment]
You are right. Can we link this issue with #175?
I was thinking to implement it separately. That time I was wrong.

**Comment by nemesisdesign** [comment]
> You are right. Can we link this issue with #175?
> I was thinking to implement it separately. That time I was wrong.

Yes, you can refer to this issue as well in 1 PR.

**Comment by niteshsinha17** [comment]
@nemesisdesign I am unable to link this with #175. I am not getting option to do this.

**Comment by nemesisdesign** [comment]
@niteshsinha17 this should have been done in #175, right? If so please close this.
