### ISSUE TITLE
[test] Write tests for register menu functionality

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#193]

**Comment by nemesisdesign** [comment]
I don't understand this issue, isn't this supposed to be part of #189?

**Comment by niteshsinha17** [comment]
Thanks, Federico for asking those questions. I will add a description in
each opened issue so you can get them easily.

**Comment by niteshsinha17** [comment]
You are right. Can we link this issue with https://github.com/openwisp/openwisp-utils/pull/175?

**Comment by nemesisdesign** [comment]
> You are right. Can we link this issue with #175?
> I was thinking to implement it separately. That time I was wrong.

Yes, you can refer to this issue as well in 1 PR.
