### ISSUE TITLE
[low-priority][improvement] Use singleton instead of global variable to store menu data

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#194]
Discussed here
1. https://github.com/openwisp/openwisp-utils/pull/175#discussion_r631213879
2. https://github.com/openwisp/openwisp-utils/pull/175#discussion_r635411208

### Conclusion 
Change the global variables used for registering menu groups and dashboard into a singleton class.

blocked by https://github.com/openwisp/openwisp-utils/pull/175

**Comment by atb00ker** [comment]
> https://github.com/openwisp/openwisp-utils/pull/175/files#r624514554

There are 2 discussions here, which one are you referring to?

**Comment by niteshsinha17** [comment]
Thanks, @atb00ker I have updated the description.

**Comment by nemesisdesign** [comment]
Let's close it. We'll reopen if we really need.
