### ISSUE TITLE
[bug] Avoid "FileExistsError" during testing

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#195]
**How to replicate**
1. Ensure your all tests passes first time.
2. Run test again and stop it before it gets completed.
3. Run test again and you will find ``file exit error`` in console.

It causes because tests create some files in the directory and those files are deleted automatically after completion of tests. When we don't let tests to complete properly then those files are not deleted so it throws error in the next run. We can delete those file manually also but I think we should find a way to handle it through the code itself.

**Comment by Aryamanz29** [comment]
I would to work on this

**Comment by Aryamanz29** [comment]
@niteshsinha17 I have done the same steps that you've mentioned above but I didn't find any errors, If possible could please share that error output.

**Comment by niteshsinha17** [comment]
@Aryamanz29 sure I will check it again and let you know.

**Comment by niteshsinha17** [comment]
@Aryamanz29 I have tested the issue is not occurring now. @nemesisdesign we can close this issue for now.
