### ISSUE TITLE
[feature] API docs theme

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#197]
The DRF browsable API and DRF Yasg theme we ship for REST APIs are quite different from one another and also different from the main theme of OpenWISP.

It would be great if we could make the DRF browsable API and DRF Yasg theme more similar to the admin theme by recyling the same CSS, so that just adding the openwisp theme css would be enough to make these look more similar.

@niteshsinha17 do you think this is doable? We could do it at the end of GSoC if there's still time.

**Comment by niteshsinha17** [comment]
Nice idea. I will do some research on it and will handle this at the end.

**Comment by Aryamanz29** [comment]
I will try this
