### ISSUE TITLE
[qa] Add commit message style check

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#20]
It's time to automate the commit message style checks according to [our guidelines](http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines), that will make contributing a lot smoother for new contributors and less time consuming for reviewers.

These are the most common issues which we should address:

- prefix not present, eg: `Done something` (should be ``[qa] Done something``)
- no capital letter after prefix: `[qa] done something`
- unnecessary final dot in first line, eg: `[qa] Done something.`
- No blank line before first line and second line, eg:
```
[qa] Done something
Long description
```
- Mentions an issue without closing it, eg: `Implements #20` (won't close), `Closes #20 and #21` (won't close `#21` - but we should allow writing something like `Related to #33`, because sometimes we may want to reference an issue even though we are not solving it in that commit
- Closes an issue in the long description but doesn't mention it in the short description, eg:
```
[qa] Done something

Fixes #2
```
should be:
```
[qa] Done something #2

Fixes #2
```
(easier to read in the short log format)

This is not urgent but not unimportant because having a clean commit history is important for the long term sustainability of the project.
It doesn't make sense to keep enforcing these rules by hand.. it's clear to me that as the community grows we won't be able to do that, so automating this check is key.

We need something like the migration check implemented in #16.

**Comment by ppabcd** [comment]
it's not clear.
