### ISSUE TITLE
[enhancement] Add bootstrap icon support

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#206]
As discussed here https://github.com/openwisp/openwisp-utils/pull/175#discussion_r640797109 need to add [Bootstrap Icons](https://icons.getbootstrap.com/) support.

blocked by:
https://github.com/openwisp/openwisp-utils/pull/175
https://github.com/openwisp/openwisp-utils/pull/185

**Comment by nemesisdesign** [comment]
@niteshsinha17 maybe we can discuss this more? Or maybe we can work on this instead: https://github.com/openwisp/openwisp-utils/issues/247, so that anybody who needs more icons can register the additional CSS they need?

**Comment by niteshsinha17** [comment]
I think we can do both so that anyone can increase icon support whenever they need it. Also, we may use #247 to register or unregister bootstrap icons if possible.

**Comment by nemesisdesign** [comment]
> I think we can do both so that anyone can increase icon support whenever they need it. Also, we may use #247 to register or unregister bootstrap icons if possible.

I am not sure we really need to do this by default, it may be stuff we add without a real need and hence will just bloat our code making maintenance painful with no real purpose.

**Comment by niteshsinha17** [comment]
Sure, Let us keep this open for the future.

**Comment by nemesisdesign** [comment]
Let's simplify our life and close this :)
