### ISSUE TITLE
[gsoc21] Show active menu item/group

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#216]
![Screenshot from 2021-07-21 21-05-14](https://user-images.githubusercontent.com/841044/126581222-e0732c0d-616a-4eba-9435-089b7b0ef90d.png)

I am in the user page here but no indication is given in the menu. It would be appropriate to highlight the current active group or menu item.
If we can also expand the current group of which the item is part would be ideal.

**Comment by niteshsinha17** [comment]
@nemesisdesign Suppose if we have the same link in different groups then what we should do? Should we highlight 1st one or all?
