### ISSUE TITLE
[gsoc21] fix unhandled exception when register a menu group

### ISSUE THREAD

**Issue by kkreitmair** [openwisp/openwisp-utils#217]
When a menu group is registered as following a exception appears.
```
register_menu_group(
    position=1,
    config={
        'model': 'test_project.Shelf',
        'name': 'changelist1', # this leads to a not revers able url
        'label': _('Shelfs'),
        'icon': 'shelf',
    },
)
```
Such a miss configuration should lead to a `ImproperlyConfigured` Exception like other menu groups miss configurations and prevent the service to come up in a improper state.

**Comment by niteshsinha17** [comment]
@kkreitmair Thanks 
I think we had discussed about this issue here https://github.com/openwisp/openwisp-utils/pull/175#discussion_r645968557

**Comment by kkreitmair** [comment]
> @kkreitmair Thanks
> I think we had discussed about this issue here [#175 (comment)](https://github.com/openwisp/openwisp-utils/pull/175#discussion_r645968557)

I have overseen this. Sorry.

In my  opinion it would be more helpful, to catch this exception and give the admin a hint about the miss configuration with the `ImproperlyConfigured` exception.

If not catching this, it takes more time to find the miss configuration within the stacktrace information of the reverse exception, because you have to go through the flow, to find the part, which causes the error.

It is not a big change, but can help a lot.

**Comment by niteshsinha17** [comment]
I agree with you. It can be more useful to display a proper error message in the terminal. What do you think? @atb00ker @nemesisdesign

**Comment by nemesisdesign** [comment]
> I agree with you. It can be more useful to display a proper error message in the terminal. What do you think? @atb00ker @nemesisdesign

Sure, that's the way to go.
