### ISSUE TITLE
[gsoc21/change] Another group is already registered at position "X"

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#227]
The error message `Another group is already registered at position "X"` is not very useufl.

We should indicate what menu item is registered and that position and which other menu item it's being registered in the same position, eg:

`A group named "Z" is being registered at position "X", but another group named "Y" is already registered at the same position.`

**Comment by niteshsinha17** [comment]
@nemesisdesign I have some concerns regarding this. 
We can register model link at a position that may not have label so it's not possible to display the name of the item being registered always.
Also, an already register element could also be a link or model link. I think we should display the message like this.

``An element with config "Z" is being registered at position "X", but another element named "Y" is already registered at the same position.``
What do you think?
