### ISSUE TITLE
[enhancement] Register sub group item

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#230]
**Discussion**
https://github.com/openwisp/openwisp-controller/pull/513#pullrequestreview-722471186

**Comment by pniaps** [comment]
Should be "unregister_menu_group" and "unregister_submenu_group" added?. Currently, to remove "VPN Servers" menu, I have to do `openwisp_utils.admin_theme.menu.MENU[30].items.pop(2)`

Also, 'Home' and 'Devices' menu are added with `register_menu_group`, while they are not groups. (is not a problem, only can be confusing)
```
register_menu_group(
    position=10,
    config={'label': _('Home'), 'url': '/admin', 'icon': 'ow-dashboard-icon'},
)
```

**Comment by nemesisdesign** [comment]
> Should be "unregister_menu_group" and "unregister_submenu_group" added?. Currently, to remove "VPN Servers" menu, I have to do `openwisp_utils.admin_theme.menu.MENU[30].items.pop(2)`
> 
> Also, 'Home' and 'Devices' menu are added with `register_menu_group`, while they are not groups. (is not a problem, only can be confusing)
> 
> ```
> register_menu_group(
>     position=10,
>     config={'label': _('Home'), 'url': '/admin', 'icon': 'ow-dashboard-icon'},
> )
> ```

I guess we could come up with a better name, maybe menu_element? And improve the naming of keyword arguments passed.
And we could use it to register either first level only or first and second, same for unregistering, there could be a way to unregister a whole group or a specific sub item.

And we need a way to add a sub element to a group.

**Comment by nemesisdesign** [comment]
A `register_menu_subitem` can a step forward with little effort that would be good for now.
