### ISSUE TITLE
[bug] OPENWISP_ADMIN_THEME_LINKS does not play well with CompressStaticFilesStorage

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#237]
I have the impression that static files defined in OPENWISP_ADMIN_THEME_LINKS do not get compressed by CompressStaticFilesStorage, I hope we can fix this.

**Comment by nemesisdesign** [comment]
Update: I think passing "href" to `static()` may fix the issue but I haven't tested it yet.
https://github.com/openwisp/openwisp-utils/blob/28459161ae54f9a6b6861f72ee6332ba0f2a40f3/openwisp_utils/admin_theme/templates/admin/base_site.html#L11

**Comment by pniaps** [comment]
> Update: I think passing "href" to `static()` may fix the issue but I haven't tested it yet.
> https://github.com/openwisp/openwisp-utils/blob/28459161ae54f9a6b6861f72ee6332ba0f2a40f3/openwisp_utils/admin_theme/templates/admin/base_site.html#L11

I have not tested your solution, but will test and make PR if works.

Right now I have solved it this way
```
        settings.OPENWISP_ADMIN_THEME_LINKS = [
            {'type': 'text/css', 'href': static('admin/css/openwisp.css'), 'rel': 'stylesheet', 'media': 'all'},
            {'type': 'text/css', 'href': static('mk-uikit.css'), 'rel': 'stylesheet', 'media': 'all'},
            {'type': 'image/x-icon', 'href': static('makedit.ico'), 'rel': 'icon'}
        ]
```

(removing `/static/` from url and using `static` function)

**Comment by nemesisdesign** [comment]
@pniaps I think we can do what you're doing there automatically, so we should be able to do it not in the template but in the python code (loop over files and call `static()` to the href attribute.

We should do the same also for the custom JS.

**Comment by pniaps** [comment]
I'm having problems with my previus message while deploying with ansible, because `collectstatic` fails the first time.

`Missing staticfiles manifest entry for ....`

**Comment by devkapilbansal** [comment]
> Update: I think passing "href" to `static()` may fix the issue but I haven't tested it yet.
> 
> https://github.com/openwisp/openwisp-utils/blob/28459161ae54f9a6b6861f72ee6332ba0f2a40f3/openwisp_utils/admin_theme/templates/admin/base_site.html#L11

I am able to load static_files by,
```
href="{% static link.href %}"
```
