### ISSUE TITLE
Conflict swapper module between utils and ipam repos 

### ISSUE THREAD

**Issue by DavidMeu** [openwisp/openwisp-utils#269]
Trying to install master IPAM:
`git+git://github.com/openwisp/openwisp-ipam@master#egg=openwisp_ipam`

```
    openwisp-ipam 0.2 depends on swapper~=1.1.0
    openwisp-utils[rest] 0.8a0 depends on swapper~=1.3.0
```

**Comment by pandafy** [comment]
This issue is not required here. I have replied to your query in https://github.com/openwisp/openwisp-ipam/issues/125#issuecomment-1004033074
