### ISSUE TITLE
[enhancement] Set body color explicitly

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-utils#272]
When the theme of the system is dark, the site is forced to use the dark theme which we don't support, hence the dashboard looks ugly.
We need to explicitly mention the color of the body to be white.

```
:root {}
```

(in openwisp.css) should fix the problem!

**Comment by Aryamanz29** [comment]
I'll would like to work on this @atb00ker

**Comment by atb00ker** [comment]
Sure, please feel free to start with it! @Aryamanz29

**Comment by atb00ker** [comment]
I tested today and following worked:

```
:root {
  --primary: inherit !important;
  --primary-fg: inherit !important;
  --body-fg: inherit !important;
  --body-bg: inherit !important;
  --body-quiet-color: inherit !important;
  --body-loud-color: inherit !important;
  --breadcrumbs-link-fg: inherit !important;
  --breadcrumbs-bg: var(--primary);
  --link-fg: inherit !important;
  --link-hover-color: inherit !important;
  --link-selected-fg: inherit !important;
  --hairline-color: inherit !important;
  --border-color: inherit !important;
  --error-fg: inherit !important;
  --message-success-bg: inherit !important;
  --message-warning-bg: inherit !important;
  --message-error-bg: inherit !important;
  --darkened-bg: inherit !important;
  --selected-bg: inherit !important;
  --selected-row: inherit !important;
  --close-button-bg: inherit !important;
  --close-button-hover-bg: inherit !important;
}
```

**Comment by atb00ker** [comment]
My suggested solutions, including `:root {}` has problems.
Please check and fix all the pages in a browser in dark mode before sending a PR! :smile:

**Comment by Aryamanz29** [comment]
> My suggested solutions, including `:root {}` has problems. Please check and fix all the pages in a browser in dark mode before sending a PR! 😄

I have used the same `:root {}` method and works perfectly fine with every page

## BEFORE 📸 

![Screenshot (239)](https://user-images.githubusercontent.com/56113566/150786226-16e4df96-98d7-47be-9cf1-d7d305fb70ff.png)

![Screenshot (244)](https://user-images.githubusercontent.com/56113566/150786210-23fe7523-fd4c-4a06-b572-646634ef886c.png)

## AFTER 📸 

![Screenshot (241)](https://user-images.githubusercontent.com/56113566/150786333-599c2fc4-d772-46f0-8606-04186de1357a.png)

![Screenshot (246)](https://user-images.githubusercontent.com/56113566/150786341-26ce3fcf-a806-4ce7-a1f3-5c2a9e294869.png)

**Comment by Aryamanz29** [comment]
> My suggested solutions, including `:root {}` has problems. Please check and fix all the pages in a browser in dark mode before sending a PR! 😄



> > My suggested solutions, including `:root {}` has problems. Please check and fix all the pages in a browser in dark mode before sending a PR! 😄
> 
> I have used the same `:root {}` method and works perfectly fine with every page
> 
> ## BEFORE 📸
> ![Screenshot (239)](https://user-images.githubusercontent.com/56113566/150786226-16e4df96-98d7-47be-9cf1-d7d305fb70ff.png)
> 
> ![Screenshot (244)](https://user-images.githubusercontent.com/56113566/150786210-23fe7523-fd4c-4a06-b572-646634ef886c.png)
> 
> ## AFTER 📸
> ![Screenshot (241)](https://user-images.githubusercontent.com/56113566/150786333-599c2fc4-d772-46f0-8606-04186de1357a.png)
> 
> ![Screenshot (246)](https://user-images.githubusercontent.com/56113566/150786341-26ce3fcf-a806-4ce7-a1f3-5c2a9e294869.png)

I have added styles to `base.html`

**Comment by Aryamanz29** [comment]
Hey @atb00ker, I have raised PR, Let me know any changes :smiley:
