### ISSUE TITLE
[qa] Add a check for empty line at the end of a file

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-utils#29]
We should add another automated test to check if all the files have an empty line at the end of the file.
Many GCI students are making this mistake and an automated test will help them in my opinion! :smile: 

PS: **binary files must be ignored**, the check should be performed only on text files.
If it can be performed with just a series of shell commands, we can use that and start adding this check to the `.travis.yml` build of this repo

**Comment by nemesisdesign** [comment]
Useful resources:

- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
- https://www.whatsdoom.com/posts/2016/09/05/finding-files-without-new-lines-at-the-end/

@atb00ker can you make and publish a GCI task for this? Maybe we can get this done before the program ends.

**Comment by ppabcd** [comment]
is it only placed in travis or with python?

**Comment by atb00ker** [comment]
You can implement it as a shell script or with python, both are fine! :smile:

**Comment by unsuitable001** [comment]
Adding `find . -type f -print0 | xargs -0 -L1 bash -c 'test "$(tail -c 1 "$0")" && exit 1`
this line to `script` section in `.travis.yml` file. Right?

**Comment by unsuitable001** [comment]
If yes, can I take the issue for other repos? & get as a task in GCI?
If yes, send me the link of GCI task instance.

**Comment by nemesisdesign** [comment]
Guys, if it can be done with a shell command, we should use that and not reinvent the wheel, in that case we should do it here in this repo first. The task is published in the GCI system.

**Comment by unsuitable001** [comment]
Can you tell how to exclude binary and byte code (e.g.. Pyc) files?

**Comment by unsuitable001** [comment]
Should I add the script to remaining repos?
