### ISSUE TITLE
Improve reusability of DependencyLoader and DependencyFinder

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#3]
`DependencyLoader` and `DependencyFinder` should allow django to reuse templates and static files of third party apps that are not loaded in `settings.INSTALLED_APPS`.

Because the original code was tied to openwisp-controller, the two classes now don't make much sense because they will go to look into `openwisp_utils.__dependencies__`.

What about creating a new setting like `EXTENDED_APPS`?

In the test suite you could add a dependency to django-netjsonconfig, then set in the test project:

```python
EXTENDED_APPS = ['django-netjsonconfig']
```

Then you could write 2 tests in which you just instantiate the 2 classes and check the list they produce is correct.

**Comment by rohithasrk** [comment]
#2 Fixes this
