### ISSUE TITLE
[bug] DRF-yasg failing collectstatic

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-utils#352]
This issue shows up when running `collectstatic` with Django >= 4.0:
```
ValueError: The file 'drf-yasg/redoc-old/redoc.min.map' could not be found with <openwisp_utils.storage.CompressStaticFilesStorage object at 0x7f1c9d231fd0>.
```

The only way I found to workaround it is to downgrade to Django~=3.2.0.

**Comment by pandafy** [comment]
[drf-yasg 1.21.7](https://drf-yasg.readthedocs.io/en/stable/changelog.html#id1) has been released. This issue should get fixed now.
