### ISSUE TITLE
Generalize easy to copy uuid, secret key and secret URL logic

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#40]
**Reserved for GSoC Students**

We have different parts of different OpenWISP modules which have a `key` or `secret` field which has one or more of the following features:

- the key is automatically and randomly generated
  - [django-netjsonconfig](https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/base/device.py#L21-L26)
  - [django-netjsongraph](https://github.com/netjson/django-netjsongraph/blob/master/django_netjsongraph/base/topology.py#L47-L53)
  - [openwisp-radius](https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/models.py#L125-L127)
  - [openwisp-controller](https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/config/models.py#L241-L247)
- the uuid field in the admin is readonly and can be copied easily:
  - [django-netjsonconfig](https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/base/admin.py#L44) (look for `uuid` and look at the javascript file)
  - [openwisp-users](https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/admin.py) (look for `uuid` and look at the javascript file)
- the key is used to build a URL which can be copied easily:
  - [django-netjsongraph](https://github.com/netjson/django-netjsongraph/blob/master/django_netjsongraph/base/admin.py#L41-L53) (look for `receive_url` and then find the `receive-url.js` javascript)

We need to:

- remove the duplication of this logic across modules and make it reusable
- add automated tests for this logic
- document its usage briefly in the README of this module
- update the other modules to use the generalized solution here in openwisp-utils

**Comment by NoumbissiValere** [comment]
Let me take a look at this

**Comment by NoumbissiValere** [comment]
@nemesisdesign please should i still remove the `receive_url` logic from `django-netjsongraph` and define it in `openwisp-utils` even though it is only defined here?

**Comment by nemesisdesign** [comment]
@NoumbissiValere it's ok now to leave django-netjsongraph, if we find out we need to reuse that code (eg: shared templates in openwisp-controller need to show the URL to users so they can copy it) we will do the same work there as well
