### ISSUE TITLE
Override django.contrib.admin.AdminSite instead of modifying it at runtime

### ISSUE THREAD

**Issue by okraits** [openwisp/openwisp-utils#42]
The function openwisp_admin() in openwisp_utils.admin_theme.admin changes some settings of the vanilla django admin site at runtime. This makes it difficult to use an overridden admin site instead of the default one together with OpenWISP.

It would be better to override the vanilla admin site instead: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#customizing-the-adminsite-class Then, for further customization, this overridden class can be overridden once more.

**Comment by nemesisdesign** [comment]
The suggested approach would be great!

**Comment by okraits** [comment]
@nemesisdesign Could this be an appropriate task for GCI?

**Comment by nemesisdesign** [comment]
One important thing: we should make sure changes will be backward compatible.
Once we finish updating this module, we will have to update the other modules.

**Comment by anshuldutt21** [comment]
Can anyone please review my PR

**Comment by nemesisdesign** [comment]
@anshuldutt21 reviewed

**Comment by anshuldutt21** [comment]
Hi @nemesisdesign please review the changes.
