### ISSUE TITLE
[docs] Document openwisp-utils-qa-check

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#47]
Add the description of `checkendline` and `openwisp-utils-qa-check` to the README, in a similar way to how the other quality assurance scripts are documented.

**Comment by TPath123** [comment]
Unlike the other individual QA checks, `checkendline` does not seem to be a command-line tool (https://github.com/openwisp/openwisp-utils/blob/master/setup.py#L35) nor is it in the [qa.py](https://github.com/openwisp/openwisp-utils/blob/master/openwisp_utils/qa.py) file

It only appears in the main `openwisp-utils-qa-check` file as a check, is this what you want me to document?

**Comment by nemesisdesign** [comment]
@TPath123 you're right, the point of the issue is that we need to document the features and usage of `openwisp-utils-qa-check`, which has been introduced without being documented. 
A bit of documentation has just been added in #60, but we need to add a general description of what it does, its purpose, its features.
