### ISSUE TITLE
[ci] Improve checkmigrations in openwisp-utils-qa-checks

### ISSUE THREAD

**Issue by marfgold1** [openwisp/openwisp-utils#52]
For now, checkmigrations in the new `openwisp-utils-qa-checks` common CI script is supported only for **one migration path and one migration-to-ignore**.
In some repo (like [django-ipam](https://github.com/openwisp/django-ipam), [django-loci](https://github.com/openwisp/django-loci), and more) it's required to check on **two migration-path**.
And even some repo (like [openwisp-users](https://github.com/openwisp/openwisp-users)) it's required to check on **two migration-path** and **two different migrations-to-ignore**.
To deal with this, we can:
1. Still using the custom `runcheckmigration` in those repo and use `openwisp-utils-qa-checks` with --skip-checkmigration. The disadvantage is, well, why should checkmigration exist in the common CI test then... :sweat_smile: 
2. The 'hacky' ways by using two lines of `openwisp-utils-qa-checks`, with the second call to check for other checkmigration and skip all tests. The disadvantage is when there is an addition/removal in the CI test, we should change those repositories too.

Either ways are fine, but kind of defeated the purpose of `openwisp-utils-qa-checks` that simplify the workflow of minor change in the CI tests without having to deal with all repositories. So I suggest that we might support multiple checkmigration, separated by semicolon. For example, we can do this for [openwisp-users](https://github.com/openwisp/openwisp-users/blob/master/runcheckmigration)

```
openwisp-utils-qa-checks --migration-path "./openwisp_users/migrations/;./tests/testapp/migrations/" --migrations-to-ignore "3;2"
```

Feel free to discuss/suggest/give your opinion about the better ways to do this :smile:

**Comment by nemesisdesign** [comment]
We can use a space delimited string, eg:

*example-script.sh*
```bash
#!/bin/bash
arr=(`echo "$@"`)

for i in "${arr[@]}"
do
   :
   echo $i
done
```

try it out:
```shell
$ chmod +x example-script.sh  # make it executable
$ ./example-script.sh "./openwisp_users/migrations/ ./tests/testapp/migrations/"
./openwisp_users/migrations/
./tests/testapp/migrations/
```

We should also update the documentation accordingly when doing #47.

**Comment by marfgold1** [comment]
@nemesisdesign Thanks for the suggestion! Yeah I've been thinking about using space as delimiter, but it seems less readable (I mean atlest with ; you can obviously see the delimiter, where space is kinda tricky to see).
I can try to fix this :smile:

**Comment by atb00ker** [comment]
@marfgold1 I'll import this to GCI by evening! :smile:
