### ISSUE TITLE
[ci] add check for pending migrations

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-utils#53]
Add a check to ensure that all the `makemigrations` are done and there is "No changes detected" in the migrations.

The command to check this would be:
- `python manage.py makemigrations --dry-run <module-name>` where is optional `<module-name>` would be passed as an arguement.

**Comment by atb00ker** [comment]
Can remove this: `https://github.com/openwisp/django-ipam/blob/5db21591c40d80b8d26630034c8116c404b63820/.travis.yml#L30` after solving this issue.

**Comment by nemesisdesign** [comment]
@atb00ker you read my mind!

We should add this, probably as a function to the openwisp-qa-checks script.

The script should capture the output, print it and ensure that `No changes detected` is present or fail (return a non zero exit code).

This issue should be resolved after https://github.com/openwisp/openwisp-utils/pull/51 is merged.

**Comment by nemesisdesign** [comment]
This feature should check for the presence of `manage.py` in the `tests` directory, if `manage.py` is not present it shall do nothing.
