### ISSUE TITLE
Improve instructions for installation during development

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/openwisp-utils#6]

**Comment by abbyck** [comment]
I would like to improve that

**Comment by nemesisdesign** [comment]
@rohithasrk could we add some detail on what needs to be done? Shall we turn this into a GCI task?

**Comment by rohithasrk** [comment]
@nemesisdesign Yeah. Can be a GCI task

**Comment by nemesisdesign** [comment]
We should replace the line `python setup.py develop` with `pip install -e .[users]`, which will automatically install openwisp-users, which depends on django and will install the right version of django.

**Comment by nemesisdesign** [comment]
Added a task for this

**Comment by abbyck** [comment]
Oops. I missed your reply @nemesisdesign. If I recall correctly I deleted a comment that I made in between that I will fix this issue. Sorry for the mention :)

**Comment by nemesisdesign** [comment]
lots of GCI students have been able to contribute to this module in the last 2 years, I think the README now is good enough so I'm closing this issue
