### ISSUE TITLE
Increasing the font size of admin UI

### ISSUE THREAD

**Issue by abbyck** [openwisp/openwisp-utils#7]
I think only the header part font is small in vision. Please give me some suggestions 

Below is a screenshot of admin ui:
![](http://sk.uploads.im/H0aG1.png)

**Comment by atb00ker** [comment]
I personally don't think it's a problem.
What's your opinion? @nemesisdesign

**Comment by abbyck** [comment]
Thanks for checking on this issue @atb00ker
This was one of the beginner tasks for GCI 2017. I personally didn't felt the need for this change initially. But in pull #8 Federico and Rohit explained it very well.

**Comment by KapilBansal320** [comment]
I don't think that this issue is still relevant now and should be closed. If the issue is relevant please provide some insights about what is needed to be done now and I would like to work on it.
