### ISSUE TITLE
[admin-theme] Allow specifying custom CSS and JS

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#79]
We should add a few settings to the `admin_theme` module allowing to supply custom CSS and JS files; these should be lists of strings containing URLs to the static files (as users may add multiple files if they need), static files have to be deployed in separate steps (this should be made clear in the README).

Settings could be named:

`OPENWISP_ADMIN_THEME_CSS` and `OPENWISP_ADMIN_JS`

As usual we need tests and docs for this feature.

**Comment by IAmAMissingColon** [comment]
Means it's kind of custom theming ?

**Comment by TheOneAboveAllTitan** [comment]
Working on it!

**Comment by TheOneAboveAllTitan** [comment]
While working on it, I developed some thoughts on how this can be made more useful. Instead of passing only URLs of static files, we can take care of static files by code. The user will have to only add the directory in STATICFILES_DIRS. I am in favor of something like this. 
```
OPENWISP_ADMIN_JS = {
    "cdn" : [
        {
            "src" : "",
            "integrity" : "",
        }
    ]
    "statics" : [
        "path/to/static/file"
    ]
}
```
This will surely make things a little more complex. What is your opinion on it?

**Comment by atb00ker** [comment]
> Instead of passing only URLs of static files, we can take care of static files by code

I am not sure if I understand this properly. :-(

**Comment by IAmAMissingColon** [comment]
Means you are saying something like the user should have an theme file saved in a particular directory and whenever the 
`"statics" : [
        "path/to/static/file"
    ]`
is triggered it will render the file present in that directory right ?

Sorry if it's wrong :smile:

**Comment by TheOneAboveAllTitan** [comment]
Yes! @IAmAMissingColon
