### ISSUE TITLE
Improve QA checks: black, re-format code, commit message check, explain in docs

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#86]
We've been spending a lot of time on code formatting during reviews lately.

In the past we discussed introducing [black](https://github.com/psf/black), I think we could start introducing it, I leave some notes here:

- add it to the QA requirements
- add it to the [QA checks](https://github.com/openwisp/openwisp-utils/blob/master/openwisp-utils-qa-checks) (ensure there's a way to skip the check)
- add a way to trigger the reformatting using isort and black (eg: `openwisp-qa-format`), so we can format the code with one command (hence making it easy for new contributors)
- update the python code convetions docs to suggest the use of `openwisp-qa-format` and `openwisp-qa-check`: http://openwisp.io/docs/developer/contributing.html#python-code-conventions
- add a flag to force the commit message check and add the suggestion of using this feature in the guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines

**Comment by PabloCastellano** [comment]
I'll try to provide a PR for this issue

**Comment by PabloCastellano** [comment]
* [x] update the python code convetions docs to suggest the use of openwisp-qa-format and openwisp-qa-check 

This is done in https://github.com/openwisp/openwisp2-docs/pull/101
