### ISSUE TITLE
Add catch_signal test utility

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#87]
- add [catch_signal from openwisp-monitoring](https://github.com/openwisp/openwisp-monitoring/blob/e3dfc323c72b7c29d6ecf7ff126dcee96da51df7/openwisp_monitoring/tests.py#L1-L11) to openwisp-utils
- add at least 1 test for it
- add a few lines of docs
- update [openwisp-controller ](https://github.com/openwisp/openwisp-controller/pull/179/files)and [openwisp-monitoring](https://github.com/openwisp/openwisp-monitoring/blob/e3dfc323c72b7c29d6ecf7ff126dcee96da51df7/openwisp_monitoring/tests.py#L1-L11) to use that and remove the duplication

**Comment by nepython** [comment]
I am working on it :smile:
