### ISSUE TITLE
[tests] Create test utility to redirect output

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-utils#98]
Recently some contributors have been confused by the fact that some tests print output to standard output and/or standard error, so they thought tests failed when tests are passing.

Let's use two context managers from the standard library to create two decorators that we'll use to decorate the test methods which produce output, the context managers are:

- [contextlib.redirect_stdout](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout)
- [contextlib.redirect_stdout](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stderr)

It should be possible to decorate test methods like the following:

```python
import sys
from openwisp_utils.tests import redirect_stdout, redirect_stderr, redirect_any_output

@redirect_stdout
def test_something_out(self):
    print('this test prints output')

@redirect_stderr
def test_something_err(self):
    print('this test prints some error', file=sys.stderr)

@redirect_any_output
def test_something_out(self):
    print('this test prints output')
    print('this test prints some error', file=sys.stderr)    
```

Sometimes we also need to check the output, so we need a way to access it, eg:

```python
@redirect_stdout(io.StringIO())
def test_something_out(self, output):
    action_generating_output()  # pseudocode
    self.assertIn('expected output', output.getvalue())

@redirect_any_output(stdout=io.StringIO(), stderr=io.StringIO())
def test_something_out(self, stdout, stderr):
    action_generating_output()  # pseudocode
    self.assertIn('expected stdout', stdout.getvalue()) 
    self.assertIn('expected stderr', stderr.getvalue())  
```

Here's a sample decorator which does not use the context managers above but which may adapted to do so: https://gist.github.com/jasonbartz/8480004

As a last step, use this decorator to silence the output of some tests in this module.

As usual, tests and (brief) docs are needed as well.

**Comment by devkapilbansal** [comment]
I will look into this issue

**Comment by devkapilbansal** [comment]
@nemesisdesign please check if this can work 
https://github.com/devkapilbansal/openwisp-utils/commit/56d60be1a7466507599294a3897bb35beb301d16
I don't think that we need context managers for it
